### PR TITLE
CZ rules and tests

### PR DESCRIPTION
**Pull request by teiwacz**
Initial upload

### CODE REVIEW

**Comment by dslmeinte** [comment]
@teiwacz There's an occurrence of a date-time string `2021-07-5T00:00:00Z` somewhere, which requires an extra '0' in front of the '5'.

**Comment by dslmeinte** [comment]
@teiwacz Are you able to run the tests locally (as described [here](https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/README.md))? That might shorten your feedback cycle considerably, also because I have to approve running the same tests as part of the CI, for every commit.

**Comment by teiwacz** [comment]
@dslmeinte  Sry for bugfix iterations. I didn't know that the pipeline is not fully automated.

**Comment by dslmeinte** [comment]
> @dslmeinte Sry for bugfix iterations. I didn't know that the pipeline is not fully automated.

No worries: clicking a button now and then is not problematic. Personally, I don't like the lag of such a process: I much rather have it also running locally - which is why I made it so that it runs locally.

**Comment by dslmeinte** [comment]
@teiwacz Checks run fine, and changes look good. Can I click the Merge-button for you?

**Comment by teiwacz** [comment]
@dslmeinte if you be that kind :)

**Pull request merged**
