### PR TITLE
HR rule sets test files 

### PR DESCRIPTION
**Pull request by kristinaleko**
HR rule sets test files

### CODE REVIEW

**Comment by kristinaleko** [comment]
@dslmeinte we should have resolved the 4 errors, these are now new test rule set files.

**Comment by dslmeinte** [comment]
@kristinaleko Can you remove the file `HR/HR.zip`? Also, the checks don't seem to trigger on this PR, which is weird. Locally they run just fine.

**Comment by kristinaleko** [comment]
@dslmeinte HR.zip deleted.

**Comment by dslmeinte** [comment]
@kristinaleko Thanks. Now the checks also showed up again. Maybe these refuse to run when a ZIP is present? Seems odd, though.

**Comment by dslmeinte** [comment]
@kristinaleko Checks ran fine, so is it OK if I merge this PR?

**Comment by kristinaleko** [comment]
@dslmeinte sure :)

**Comment by dslmeinte** [comment]
@kristinaleko Done :)

**Comment by kristinaleko** [comment]
@dslmeinte btw the trouble with upload was generated by internal network ofcourse 😅 it's always the network..

Anyway we can now switch the changes into the production on the DGCG

**Comment by dslmeinte** [comment]
@kristinaleko Good to hear that's sorted out as well!

**Pull request merged**
