### PR TITLE
[ES] Added new BRs due to changes on boosters

### PR DESCRIPTION
**Pull request by Santivicen**

### CODE REVIEW

**Comment by Santivicen** [comment]
I see test has failed. I will check with team.

**Comment by dslmeinte** [comment]
@Santivicen Apparently the file `TR-ES-0002.json` is not parsable as JSON at position 0. Could you check whether you inadvertently inserted a BOM marker?

**Comment by Santivicen** [comment]
> @Santivicen Apparently the file `TR-ES-0002.json` is not parsable as JSON at position 0. Could you check whether you inadvertently inserted a BOM marker?

That was true. 2 of them. Thanks!

**Comment by Santivicen** [comment]
I see there are errors on the rules. I will check with team, to be sure that files were the right one (and testes locally).

**Comment by dslmeinte** [comment]
@Santivicen No need to demolish the PR. Take your time finding out what's going.

**Comment by dslmeinte** [comment]
@Santivicen Shall I merge? (I suspect you don't have the necessary rights yourself.)

**Pull request merged**
