### PR TITLE
PL business rules

### PR DESCRIPTION
**Pull request by rafalgra**

### CODE REVIEW

**Comment by dslmeinte** [comment]
It seems you've copied the `VR-DE-0003` rule, but somehow removed the <else> operand of an `if` in there.

**Comment by rafalgra** [comment]
Probably, certlogic expression:
```
{
    "if": [
      {
        "var": "payload.v.0"
      },
      {
        "if": [
          {
            "not-before": [
              {
                "plusTime": [
                  {
                    "var": "external.validationClock"
                  },
                  0,
                  "day"
                ]
              },
              {
                "plusTime": [
                  {
                    "var": "payload.v.0.dt"
                  },
                  14,
                  "day"
                ]
              }
            ]
          },
          true,
          {
            "if": [
              {
                ">": [
                  {
                    "var": "payload.v.0.dn"
                  },
                  2
                ]
              },
              true,
              {
                "if": [
                  {
                    "and": [
                      {
                        ">": [
                          {
                            "var": "payload.v.0.dn"
                          },
                          1
                        ]
                      },
                      {
                        "===": [
                          {
                            "var": "payload.v.0.mp"
                          },
                          "EU/1/20/1525"
                        ]
                      }
                    ]
                  },
                  true,
				  false
                ]
              }
            ]
          }
        ]
      },
      true
    ]
  }
```

**Review by dslmeinte — APPROVED** [review]

**Comment by rafalgra** [comment]
Thanks for your help. I checked the rule with https://certlogic-fiddle.vercel.app/

**Comment by rafalgra** [comment]
I probably don't have merge permissions - but I see that you merged it, thanks you @dslmeinte

**Pull request merged**
