### PR TITLE
rules from AT v5

### PR DESCRIPTION
**Pull request by chris-baumann-at**

### CODE REVIEW

**Comment by dslmeinte** [comment]
@chris-baumann-at  I would've expected the `Version` field to be bumped for this, if only because the version can't be uploaded otherwise. What do you think?

**Comment by chris-baumann-at** [comment]
> 
> 
> @chris-baumann-at I would've expected the `Version` field to be bumped for this, if only because the version can't be uploaded otherwise. What do you think?

Yes, you are right.
But we have another tool which prepears the rule files for the upload (and that changes the version and also the validity dates and the "region" field). I am just testing the current workflow ... hope this is OK ...

**Review by dslmeinte — APPROVED** [review]

**Comment by dslmeinte** [comment]
@chris-baumann-at Thanks for the clarification: all OK + Approved. Can you merge the PR yourself?

Could you share this other tool you mentioned somehow? I think it's beneficial to share such tools as much as possible, to potentially align processes and save effort through reuse.

**Comment by chris-baumann-at** [comment]
> 
>
> @chris-baumann-at Thanks for the clarification: all OK + Approved. Can you merge the PR yourself?
> 
@dslmeinte I cant' (am not allowed to) merge. Thanks for merging instead of me ;-)

**Pull request merged**
